---
name: Publish collection to Ansible Galaxy

on:
  release:
    types:
      - released

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: 'Release on galaxy'
        uses: ansible-actions/ansible-galaxy-action@v1.2.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_TOKEN }}
          galaxy_version: ${{ github.event.release.tag_name }}
